export const emotionOptions = [
  {
    id: 'anxious',
    emoji: '⚡',
    label: 'Anxious',
    description: 'Racing thoughts, worry, tension.',
    interventionTitle: 'Ground your thoughts and slow your system.',
    interventionDetails: 'Try 4-4-6 breathing for two minutes. Label one worry as a thought, not a fact. Then choose one small step that feels manageable right now.',
    interventionSlug: 'physiological-sigh',
    variant: 'act',
  },
  {
    id: 'overwhelmed',
    emoji: '🌊',
    label: 'Overwhelmed',
    description: 'Too much at once, minds feels flooded.',
    interventionTitle: 'Create a small, steady reset.',
    interventionDetails: 'Pause and name three things you can control in this moment. Break the next task into one tiny step and let the rest wait.',
    variant: 'behavioral',
  },
  {
    id: 'stressed',
    emoji: '⏰',
    label: 'Stressed',
    description: 'Pressure, deadlines, tension.',
    interventionTitle: 'Shift from overwhelm to action.',
    interventionDetails: 'Use a quick body scan and a breathing anchor. Ask yourself: what is one thing I can do in the next five minutes that eases this pressure?',
    variant: 'cbt',
  },
  {
    id: 'sad',
    emoji: '🌧',
    label: 'Sad',
    description: 'Heavy, low, tearful, quiet.',
    interventionTitle: 'Hold the feeling with gentle care.',
    interventionDetails: 'Acknowledge that sadness is valid. Name one thing you can do that feels kind, even if it is small: a warm drink, a walk, or a quiet moment.',
    variant: 'somatic',
  },
  {
    id: 'angry',
    emoji: '🔥',
    label: 'Angry',
    description: 'Frustrated, irritable, lashing out.',
    interventionTitle: 'Let the heat land without reacting.',
    interventionDetails: 'Pause and notice what your body is doing. Count to six, then choose whether you need space, a boundary, or a calm statement.',
    variant: 'dbt',
  },
  {
    id: 'lonely',
    emoji: '🌑',
    label: 'Lonely',
    description: 'Disconnected, unseen, isolated.',
    interventionTitle: 'Reach for connection in a small, safe way.',
    interventionDetails: 'Name one person you trust, even if you don’t reach out yet. If you can, send a simple message or plan one small social step.',    interventionSlug: 'body-scan',    variant: 'psychoed',
  },
  {
    id: 'numb',
    emoji: '🧊',
    label: 'Numb',
    description: 'Flat, disconnected, empty.',
    interventionTitle: 'Bring your senses back online.',
    interventionDetails: 'Try a grounding exercise: hold something textured, breathe deeply, and name five sensations in your body. The goal is to reconnect without forcing feeling.',
    interventionSlug: '54321-grounding',
    variant: 'somatic',
  },
  {
    id: 'grief',
    emoji: '🕊️',
    label: 'Grief',
    description: 'Missing someone or something deeply.',
    interventionTitle: 'Allow the ache instead of fixing it.',
    interventionDetails: 'Spend a few moments naming what you miss. Offer yourself the kindness you would give a friend in pain. You do not have to make this go away.',
    variant: 'act',
  },
  {
    id: 'unmotivated',
    emoji: '🪫',
    label: 'Unmotivated',
    description: 'Flat, stuck, unable to start.',
    interventionTitle: 'Start with one tiny, doable action.',
    interventionDetails: 'Pick the smallest possible next step — five minutes, one sentence, one short walk. Action often creates momentum, even when motivation is absent.',
    variant: 'behavioral',
  },
  {
    id: 'relationship',
    emoji: '💔',
    label: 'Relationship',
    description: 'Conflict, hurt, distance, disconnection.',
    interventionTitle: 'Hold compassion for yourself and the other person.',
    interventionDetails: 'Name what you need and what the other person might need. Then decide whether you need space, a boundary, or a calm conversation.',
    variant: 'cbt',
  },
  {
    id: 'self-worth',
    emoji: '🎭',
    label: 'Self-Worth',
    description: 'Feeling unworthy, ashamed, not enough.',
    interventionTitle: 'Separate fact from the harsh story.',
    interventionDetails: 'Notice one thought that says you are not enough. Ask: is that always true? Evidence often shows a kinder, more balanced story.',
    variant: 'cbt',
  },
  {
    id: 'self-destructive',
    emoji: '🩹',
    label: 'Self-Destructive',
    description: 'Urges to hurt yourself, feel unsafe, or disappear.',
    interventionTitle: 'Get help now — this is an emergency.',
    interventionDetails: 'If you are in danger or thinking about harming yourself, call or text 988 immediately. You deserve immediate support from a real person. Stay with someone and use a safe person list if you have one.',
    crisis: true,
    variant: 'viral',
  },
];

export const contextOptions = [
  { id: 'mind', label: 'Mind racing' },
  { id: 'body', label: 'Body tight' },
  { id: 'avoidance', label: 'Avoiding something' },
  { id: 'alone', label: 'Feeling alone' },
];
