export const emotionOptions = [
  {
    id: 'anxious',
    emoji: '😰',
    label: 'Anxious',
    shortLabel: 'Anxious',
    description: 'Racing thoughts, worry, tension.',
    color: 'ocean',
    accent: 'var(--ocean)',
    accentDeep: 'var(--ocean-deep)',
    accentLight: 'var(--ocean-light)',
    variant: 'cbt',
  },
  {
    id: 'sad-low',
    emoji: '😢',
    label: 'Sad / Low',
    shortLabel: 'Sad',
    description: 'Heavy, low, tearful, quiet.',
    color: 'lavender',
    accent: 'var(--lavender)',
    accentDeep: 'var(--lavender-deep)',
    accentLight: 'var(--lavender-light)',
    variant: 'dbt',
  },
  {
    id: 'angry',
    emoji: '😤',
    label: 'Angry',
    shortLabel: 'Angry',
    description: 'Frustrated, hot, reactive, ready to snap.',
    color: 'clay',
    accent: 'var(--error)',
    accentDeep: '#8F3F3F',
    accentLight: 'rgba(196, 91, 91, 0.12)',
    variant: 'somatic',
  },
  {
    id: 'overwhelmed',
    emoji: '😵‍💫',
    label: 'Overwhelmed',
    shortLabel: 'Overwhelmed',
    description: 'Too much at once, flooded, overloaded.',
    color: 'lavender',
    accent: 'var(--lavender)',
    accentDeep: 'var(--lavender-deep)',
    accentLight: 'var(--lavender-light)',
    variant: 'dbt',
  },
  {
    id: 'shame-guilt',
    emoji: '😔',
    label: 'Shame / Guilt',
    shortLabel: 'Shame',
    description: 'Self-blame, regret, feeling not enough.',
    color: 'rose',
    accent: 'var(--rose)',
    accentDeep: 'var(--rose-deep)',
    accentLight: 'var(--rose-light)',
    variant: 'psychoed',
  },
  {
    id: 'grief-loss',
    emoji: '💔',
    label: 'Grief / Loss',
    shortLabel: 'Grief',
    description: 'Missing someone or something deeply.',
    color: 'lavender',
    accent: 'var(--lavender)',
    accentDeep: 'var(--lavender-deep)',
    accentLight: 'var(--lavender-light)',
    variant: 'act',
  },
  {
    id: 'numb-disconnected',
    emoji: '😶',
    label: 'Numb / Disconnected',
    shortLabel: 'Numb',
    description: 'Flat, distant, checked out, not quite here.',
    color: 'muted',
    accent: 'var(--ink-muted)',
    accentDeep: 'var(--ink-soft)',
    accentLight: 'rgba(138, 128, 120, 0.12)',
    variant: 'somatic',
  },
  {
    id: 'lonely',
    emoji: '😟',
    label: 'Lonely',
    shortLabel: 'Lonely',
    description: 'Disconnected, unseen, isolated.',
    color: 'ocean',
    accent: 'var(--ocean)',
    accentDeep: 'var(--ocean-deep)',
    accentLight: 'var(--ocean-light)',
    variant: 'cbt',
  },
  {
    id: 'stressed-burned-out',
    emoji: '😫',
    label: 'Stressed / Burned Out',
    shortLabel: 'Stressed',
    description: 'Pressure, depletion, deadlines, tension.',
    color: 'amber',
    accent: 'var(--amber)',
    accentDeep: 'var(--amber-deep)',
    accentLight: 'var(--amber-light)',
    variant: 'behavioral',
  },
  {
    id: 'scared-fearful',
    emoji: '😨',
    label: 'Scared / Fearful',
    shortLabel: 'Scared',
    description: 'Threatened, unsafe, bracing for what might happen.',
    color: 'clay',
    accent: 'var(--clay)',
    accentDeep: 'var(--clay-deep)',
    accentLight: 'var(--clay-light)',
    variant: 'somatic',
  },
  {
    id: 'stuck-lost',
    emoji: '🙃',
    label: 'Stuck / Lost',
    shortLabel: 'Stuck',
    description: 'Unsure, blocked, unable to choose the next step.',
    color: 'amber',
    accent: 'var(--amber)',
    accentDeep: 'var(--amber-deep)',
    accentLight: 'var(--amber-light)',
    variant: 'behavioral',
  },
  {
    id: 'self-destructive',
    emoji: '🫠',
    label: 'Self-Destructive',
    shortLabel: 'Self-Destructive',
    description: 'Urges to hurt yourself, disappear, or not be here.',
    color: 'rose',
    accent: 'var(--rose)',
    accentDeep: 'var(--rose-deep)',
    accentLight: 'var(--rose-light)',
    crisis: true,
    variant: 'viral',
  },
];

export const timePreferences = [
  {
    id: 'quick',
    label: 'Quick',
    duration: '1-2 min',
    description: 'A fast reset. Perfect for right now.',
    emoji: '⚡',
  },
  {
    id: 'medium',
    label: 'Medium',
    duration: '5-10 min',
    description: 'A deeper dive. Space to actually work through it.',
    emoji: '🔄',
  },
  {
    id: 'deep',
    label: 'Deep',
    duration: '15-25 min',
    description: 'A full session. Real tools, real shifts.',
    emoji: '🌊',
  },
];

export const intensityLabels = [
  { value: 1, label: 'Barely there' },
  { value: 4, label: 'Noticeable' },
  { value: 7, label: 'Strong' },
  { value: 10, label: 'Overwhelming' },
];

export const contextOptions = [];
